site_name: performance_assessor

nav:
    - Home: index.md
    - parse_argument:
          - check_argument.py: parse_argument/check_argument.md
          - define_argument.py: parse_argument/define_argument.md
          - parse_argument.py: parse_argument/parse_argument.md
    - class_performance_assessor.py: class_performance_assessor.md
    - main.py: main.md
    - testor.py: testor.md

repo_url: https://github.com/FilouPlains/performance_assessor

markdown_extensions:
    - nl2br
    - admonition
    - pymdownx.details
    - pymdownx.superfences

plugins:
    - search
    - mkdocstrings
    - callouts

theme:
    name: material
    palette:
        primary: red
        scheme: default
    highlightjs: true
    hljs_languages:
        - bash
        - python
    font:
        text: Roboto Light

extra_css:
    - style.css
