name: Uploading on PyPi

on:
    release:
        types: [published]

permissions:
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - shell: bash
              env:
                  PIPY_TOKEN: ${{ secrets.PIPY_TOKEN }}
                  SECRET: ${{ secrets }}
              run: |
                  echo "toto-$PIPY_TOKEN-tata"
                  echo "toto-$SECRET-tata"
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"
            - name: Install build dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install build
            - name: Build package
              run: python -m build
            - name: Store the distribution packages
              uses: actions/upload-artifact@v3
              with:
                  name: python-package-distributions
                  path: dist/
            - name: Install build dependencies
              run: |
                  python3 -m pip install --upgrade twine
            - name: Publish Python package to PyPi
              env: # Or as an environment variable
              run: |
                  python3 -m twine upload --repository pypi dist/* -u __token__ -p "$PIPY_TOKEN"
