# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package on PyPi

on:
    release:
        types: [published]

permissions:
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"
            - name: Install build dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install build
            - name: Build package
              run: python -m build
            - name: Store the distribution packages
              uses: actions/upload-artifact@v3
              with:
                  name: python-package-distributions
                  path: dist/
            - name: Install build dependencies
              run: |
                  python3 -m pip install --upgrade twine
            - name: Publish Python package to PyPi
              env: # Or as an environment variable
                  PIPY_TOKEN: ${{ secrets.PIPY_TOKEN }}
              run: |
                  python3 -m twine upload --repository pypi dist/* -u __token__ -p "$PIPY_TOKEN"
